version: '{build}'
configuration: Release
before_build:
  - nuget restore
artifacts:
  - path: PlatformTabbedPage.1.0.0-b.nupkg
    name: nuget_pack
after_build:
  - nuget pack "PlatformTabbedPage.nuspec"
image: Visual Studio 2017 
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0'
  assembly_file_version: '1.0.0'
  assembly_informational_version: '1.0.0'
build:
  project: PlatformTabbedPage.sln
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: XImXaAhmv7juP3N1QLgjU+V2u1+QjEXJnj3mv3U1uCjSzOa8c+LTl2KP3s/ClxhJ
  artifact: /.*\.nupkg/
  on:
    branch: master